# Usa la imagen oficial de MySQL como base
FROM mysql:8.0

# Establece variables de entorno para inicializar la base de datos
ENV MYSQL_ROOT_PASSWORD=*****
ENV MYSQL_DATABASE=my_datab
ENV MYSQL_USER=magnetEm
ENV MYSQL_PASSWORD=Letra123
